# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Building and Pushing the Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

#    - name: Configure AWS credentials
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: ${{ secrets.AWS_REGION }}

#    - name: Login to Amazon ECR
#      id: login-ecr
#      uses: aws-actions/amazon-ecr-login@v1

#    - name: Build, tag, and push image to Amazon ECR
#      id: build-image
#      env:
#        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#        ECR_REPOSITORY: argo-cd-samle-web

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINERREGISTERTOKEN }}

    - name: Build, tag, and push image to registory
      id: build-image
      run: |
        # Build a docker container and push it to registry
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        docker build -t ghcr.io/${{github.actor}}/${{secrets.PACKAGE}}:${GITHUB_REF##*/}-$git_hash .
        echo "Pushing image to registery..."
        docker push ghcr.io/${{github.actor}}/${{secrets.PACKAGE}}:${GITHUB_REF##*/}-$git_hash
        echo "::set-output name=image::ghcr.io/${{github.actor}}/${{secrets.PACKAGE}}:${GITHUB_REF##*/}-$git_hash"
        
        
    - name: Update image
      run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          image=$(cat ./gitOps/deployment.yaml | grep image: | awk -F ":" '{print $NF}')
          sed -i "s/$image/${GITHUB_REF##*/}-$git_hash/" ./gitOps/deployment.yaml
          
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.GITACTIONS }}
        commit_message: image updated
        force: true
